### ISSUE TITLE
small issue

### ISSUE THREAD

**Issue by afffsrsgd** [regiellis/ComfyUI-EasyNoobai#1]
Thank you for the Node; it's working wonderfully, and I hope it reaches more people. However, there's a small issue: not all artists are available, like superbusty.
Will you be developing the Node further in the future?

**Comment by regiellis** [comment]
@afffsrsgd 
Thanks

The artist may not be available in the initial compiled list. This was something I addressed in the readme file. The dataset lists are very large (260000+) entries . This is too much for Comfy to load in the filter dropdown list, I wrote a script to only compile a small percentage of the list for use. The script can be found in the assets folder and ran to recompile the list to get more artist. I need to detail more on how to use it...

As a work around...you can use the prefix of the Artist node to include any author not in the list. Just don't select any artist in the list and it should added it.

I think I will make a video on how to use the node
